services:
  kafka:
    image: apache/kafka:3.7.0
    container_name: kafka
    restart: unless-stopped
    mem_limit: 1500m

    ports:
      - "9092:9092"

    environment:
      # --------------------
      # KRaft 기본 설정
      # --------------------
      KAFKA_NODE_ID: 1
      KAFKA_PROCESS_ROLES: broker, controller
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@localhost:9093

      # --------------------
      # Listener 설정
      # --------------------
      KAFKA_LISTENERS: PLAINTEXT://:9092,CONTROLLER://:9093
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://${HOST_IP}:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT

      # --------------------
      # KRaft 필수
      # --------------------
      KAFKA_KRAFT_CLUSTER_ID: 'MkU3OEVBNTcwNTJENDM2Qk'

      # --------------------
      # 단일 브로커 설정
      # --------------------
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
      KAFKA_NUM_PARTITIONS: 1
      KAFKA_MIN_INSYNC_REPLICAS: 1

      KAFKA_HEAP_OPTS: "-Xms512M -Xmx512M"

      # --------------------
      # 로그 설정
      # --------------------
      KAFKA_LOG_RETENTION_HOURS: 168
      KAFKA_LOG_RETENTION_BYTES: 1073741824
      KAFKA_LOG_SEGMENT_BYTES: 268435456
      KAFKA_LOG_CLEANUP_POLICY: delete
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "true"

    volumes:
      - ./kafka_data:/var/lib/kafka/data

    networks:
      - app-network

# 네트워크 정의 (Redis 등 다른 컨테이너와 통신을 위해)
networks:
  app-network:
    driver: bridge