server:
  port: 8082

spring:
  application:
    name: mopl-batch
  profiles:
    include:
      - common
      - persistence
    active: ${SPRING_PROFILES_ACTIVE:dev}
    group:
      dev: persistence-dev, common-dev
      prod: persistence-prod, common-prod
