spring:
  application:
    name: mopl-persistence
  config:
    import: optional:file:.env[.properties], optional:file:../.env[.properties]

  jpa:
    open-in-view: false
    properties:
      hibernate:
        default_batch_fetch_size: 100

  data:
    redis:
      repositories:
        enabled: true

  cloud:
    aws:
      s3:
        bucket: ${AWS_S3_BUCKET}
      region:
        static: ${AWS_REGION}
      stack:
        auto: false