spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/mopl?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=Asia/Seoul
    username: mopl
    password: mopl1234

  sql:
    init:
      mode: never

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  data:
    redis:
      host: localhost
      port: 6379
