server:
  port: 8081

spring:
  application:
    name: mopl-realtime
  profiles:
    include: persistence
    active: ${SPRING_PROFILES_ACTIVE:dev}
    group:
      dev: persistence-dev
      prod: persistence-prod
