server:
  port: 8081

spring:
  application:
    name: mopl-realtime
  profiles:
    include: common
    active: ${SPRING_PROFILES_ACTIVE:dev}
    group:
      dev: common-dev
      prod: common-prod
